'use client';

import { useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import { LocationPicker } from '@/components/shared/location-picker';
import { WizardSteps } from '@/components/dashboard/wizard-steps';
import { createPropertyAction } from '@/app/actions/property-actions';
import { updatePropertyAction } from '@/app/actions/property-actions';
import { createClient } from '@/lib/supabase/client';
import type { Profile } from '@/lib/auth/get-current-profile';
import { PROPERTY_TYPE_OPTIONS } from '@/lib/listing-constants';
import * as Icons from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

interface AmenityOption { id: string; label: string; icon: string | null; category: string | null }
interface PhotoItem { id: string; file: File; previewUrl: string }
type StepId = 'type' | 'mode' | 'capacity' | 'amenities' | 'long-term' | 'details' | 'location' | 'photos' | 'contact';
const CATEGORIES = [{ key: 'general', label: 'Général' }, { key: 'exterieur', label: 'Extérieur' }, { key: 'cuisine', label: 'Cuisine' }, { key: 'securite', label: 'Sécurité' }];

function amenityCategory(category: string | null): string {
  const normalized = (category || 'general').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
  return CATEGORIES.some((item) => item.key === normalized) ? normalized : 'general';
}

function iconFor(name: string | null): LucideIcon {
  if (!name) return Icons.Sparkles;
  const pascal = name.replace(/(^|[-_\s])([a-z])/g, (_, p, c) => `${p}${c.toUpperCase()}`);
  return (Icons as unknown as Record<string, LucideIcon>)[pascal] || Icons.Sparkles;
}
function NumberField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="block min-w-0"><span className="mb-1 block text-sm font-medium text-navy-700">{label}</span><input type="number" min="0" value={value} onChange={(e) => onChange(e.target.value)} className="w-full min-w-0 min-h-[44px] rounded-lg border border-navy-100 px-3 text-base text-navy-800 focus:outline-none focus:ring-2 focus:ring-sun-400" /></label>;
}
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<string | { value: string; label: string }> }) {
  return <label className="block min-w-0"><span className="mb-1 block text-sm font-medium text-navy-700">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="w-full min-w-0 min-h-[44px] rounded-lg border border-navy-100 bg-white px-3 text-base text-navy-800"><option value="">Sélectionner</option>{options.map((option) => { const normalized = typeof option === 'string' ? { value: option, label: option } : option; return <option key={normalized.value} value={normalized.value}>{normalized.label}</option>; })}</select></label>;
}
function TriStateField({ label, value, onChange }: { label: string; value: boolean | null; onChange: (value: boolean | null) => void }) {
  return <div className="min-w-0"><span className="mb-2 block text-base text-navy-700">{label}</span><div className="grid grid-cols-3 gap-2">{([{ value: true, label: 'Oui' }, { value: false, label: 'Non' }, { value: null, label: 'Non précisé' }] as const).map((option) => <button key={option.label} type="button" onClick={() => onChange(option.value)} className={`min-h-[44px] rounded-lg border px-2 text-sm ${value === option.value ? 'border-sun-500 bg-sun-50 ring-2 ring-sun-300' : 'border-navy-100'}`}>{option.label}</button>)}</div></div>;
}
function Screen({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="space-y-5"><div><h2 className="font-display text-2xl font-bold text-navy-800">{title}</h2><p className="mt-1 text-base text-navy-500">Une étape à la fois, pour une annonce claire et complète.</p></div>{children}</section>;
}

export function LogementWizard({ profile, amenities, initialProperty, existingPhotoCount = 0 }: { profile: Profile; amenities: AmenityOption[]; initialProperty?: any; existingPhotoCount?: number }) {
  const [step, setStep] = useState<StepId>('type'); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const [type, setType] = useState(initialProperty?.type === 'hotel' ? 'appartement_studio' : (initialProperty?.type || 'appartement_studio')); const [rentalMode, setRentalMode] = useState(initialProperty?.rental_mode || 'courte_duree'); const [pricePerNight, setPricePerNight] = useState(initialProperty?.price_per_night ? String(initialProperty.price_per_night) : ''); const [pricePerMonth, setPricePerMonth] = useState(initialProperty?.price_per_month ? String(initialProperty.price_per_month) : ''); const [minMonths, setMinMonths] = useState(initialProperty?.min_months ? String(initialProperty.min_months) : '1');
  const [capacity, setCapacity] = useState(initialProperty?.capacity ? String(initialProperty.capacity) : '2'); const [bedrooms, setBedrooms] = useState(initialProperty?.bedrooms ? String(initialProperty.bedrooms) : '1'); const [livingRooms, setLivingRooms] = useState(initialProperty?.living_rooms ? String(initialProperty.living_rooms) : '0'); const [bathrooms, setBathrooms] = useState(initialProperty?.bathrooms ? String(initialProperty.bathrooms) : '1'); const [privateBathroom, setPrivateBathroom] = useState('private'); const [showerType, setShowerType] = useState('interne');
  const [depositAmount, setDepositAmount] = useState(initialProperty?.deposit_amount ? String(initialProperty.deposit_amount) : ''); const [advanceMonths, setAdvanceMonths] = useState(initialProperty?.advance_months ? String(initialProperty.advance_months) : ''); const [electricityType, setElectricityType] = useState(initialProperty?.electricity_type || ''); const [waterSource, setWaterSource] = useState(initialProperty?.water_source || ''); const [roadAccess, setRoadAccess] = useState(initialProperty?.road_access || ''); const [isFenced, setIsFenced] = useState<boolean | null>(initialProperty?.is_fenced ?? null); const [hasGate, setHasGate] = useState<boolean | null>(initialProperty?.has_gate ?? null); const [isFurnished, setIsFurnished] = useState<boolean | null>(initialProperty?.is_furnished ?? null);
  const [selectedAmenities, setSelectedAmenities] = useState<string[]>(initialProperty?.selectedAmenityIds || []); const [title, setTitle] = useState(initialProperty?.title || ''); const [description, setDescription] = useState(initialProperty?.description || ''); const [houseRules, setHouseRules] = useState((initialProperty?.house_rules || []).join('\n')); const [quartier, setQuartier] = useState(initialProperty?.quartier || ''); const [address, setAddress] = useState(initialProperty?.address || ''); const [latitude, setLatitude] = useState<number | null>(initialProperty?.latitude || null); const [longitude, setLongitude] = useState<number | null>(initialProperty?.longitude || null); const [photos, setPhotos] = useState<PhotoItem[]>([]); const [contactPhone, setContactPhone] = useState(profile.phone || '');
  const isLongTerm = rentalMode === 'longue_duree' || rentalMode === 'les_deux';
  const steps = useMemo(() => (['type', 'mode', 'capacity', 'amenities', ...(isLongTerm ? ['long-term'] : []), 'details', 'location', 'photos', 'contact'] as StepId[]), [isLongTerm]);
  const stepIndex = steps.indexOf(step); const goTo = (index: number) => setStep(steps[Math.max(0, Math.min(index, steps.length - 1))]);
  const validate = () => {
    if (step === 'mode' && ((rentalMode !== 'longue_duree' && (!pricePerNight || Number(pricePerNight) <= 0)) || (isLongTerm && (!pricePerMonth || Number(pricePerMonth) <= 0 || !minMonths || Number(minMonths) < 1)))) return 'Renseignez les tarifs requis.';
    if (step === 'long-term' && (!depositAmount || Number(depositAmount) < 0)) return 'Indiquez le montant de la caution.';
    if (step === 'capacity' && (!capacity || Number(capacity) < 1)) return 'Indiquez une capacité valide.';
    if (step === 'details' && !title.trim()) return "Saisissez le titre de l'annonce.";
    if (step === 'location' && !quartier.trim()) return 'Précisez le quartier.';
    if (step === 'photos' && photos.length + existingPhotoCount === 0) return 'Ajoutez au moins une photo.';
    if (step === 'contact' && !contactPhone.trim()) return 'Indiquez un téléphone de contact.';
    return null;
  };
  const handleNext = () => { const message = validate(); if (message) { setError(message); return; } setError(null); goTo(stepIndex + 1); };
  const handlePhotoSelect = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []).slice(0, 5 - photos.length); setPhotos((current) => [...current, ...files.map((file) => ({ id: crypto.randomUUID(), file, previewUrl: URL.createObjectURL(file) }))]); event.target.value = ''; };
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const message = validate(); if (message) { setError(message); return; } const formData = new FormData(event.currentTarget); setSubmitting(true); try { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Session expirée.'); if (initialProperty?.id) formData.append('property_id', initialProperty.id); for (const photo of photos) { const ext = photo.file.name.split('.').pop() || 'jpg'; const path = `${user.id}/${crypto.randomUUID()}.${ext}`; const { error: uploadError } = await supabase.storage.from('listings').upload(path, photo.file, { cacheControl: '3600', upsert: false }); if (uploadError) throw uploadError; formData.append('image_urls', supabase.storage.from('listings').getPublicUrl(path).data.publicUrl); } await (initialProperty?.id ? updatePropertyAction(formData) : createPropertyAction(formData)); } catch (err: any) { if (!err?.message?.includes('NEXT_REDIRECT')) { setError(err?.message || 'Erreur de publication.'); setSubmitting(false); } } };
  const selectedTypeLabel = PROPERTY_TYPE_OPTIONS.find((item) => item.value === type)?.label || type;
  return <div className="rounded-2xl border border-navy-100 bg-white p-4 shadow-sm sm:p-8"><WizardSteps currentStep={stepIndex + 1} totalSteps={steps.length} />
    <form onSubmit={handleSubmit}><input type="hidden" name="type" value={type} /><input type="hidden" name="rental_mode" value={rentalMode} /><input type="hidden" name="price_per_night" value={pricePerNight} /><input type="hidden" name="price_per_month" value={pricePerMonth} /><input type="hidden" name="min_months" value={minMonths} /><input type="hidden" name="capacity" value={capacity} /><input type="hidden" name="bedrooms" value={type === 'chambre' ? '1' : bedrooms} /><input type="hidden" name="living_rooms" value={type === 'chambre' ? '0' : livingRooms} /><input type="hidden" name="bathrooms" value={bathrooms} /><input type="hidden" name="private_bathroom" value={privateBathroom} /><input type="hidden" name="shower_type" value={showerType} /><input type="hidden" name="deposit_amount" value={depositAmount} /><input type="hidden" name="advance_months" value={advanceMonths} /><input type="hidden" name="electricity_type" value={electricityType} /><input type="hidden" name="water_source" value={waterSource} /><input type="hidden" name="road_access" value={roadAccess} /><input type="hidden" name="is_fenced" value={isFenced === null ? '' : String(isFenced)} /><input type="hidden" name="has_gate" value={hasGate === null ? '' : String(hasGate)} /><input type="hidden" name="is_furnished" value={isFurnished === null ? '' : String(isFurnished)} /><input type="hidden" name="title" value={title} /><input type="hidden" name="description" value={description} /><input type="hidden" name="house_rules" value={houseRules} /><input type="hidden" name="quartier" value={quartier} /><input type="hidden" name="address" value={address} /><input type="hidden" name="latitude" value={latitude ?? ''} /><input type="hidden" name="longitude" value={longitude ?? ''} />{selectedAmenities.map((id) => <input key={id} type="hidden" name="amenities" value={id} />)}
      {step === 'type' && <Screen title="Quel type de logement proposez-vous?"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{PROPERTY_TYPE_OPTIONS.map((item) => <button key={item.value} type="button" onClick={() => setType(item.value)} className={`min-h-[64px] rounded-xl border p-4 text-left font-semibold ${type === item.value ? 'border-sun-500 bg-sun-50 ring-2 ring-sun-300' : 'border-navy-100'}`}>{item.label}</button>)}</div></Screen>}
      {step === 'mode' && <Screen title="Comment souhaitez-vous louer ce logement?"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[{ value: 'courte_duree', label: 'Courte durée', desc: 'Tarif à la nuitée' }, { value: 'longue_duree', label: 'Longue durée', desc: 'Tarif mensuel' }, { value: 'les_deux', label: 'Les deux', desc: 'Nuitée ou mois' }].map((item) => <button key={item.value} type="button" onClick={() => setRentalMode(item.value)} className={`min-h-[76px] rounded-xl border p-3 text-left ${rentalMode === item.value ? 'border-sun-500 bg-sun-50 ring-2 ring-sun-300' : 'border-navy-100'}`}><span className="block font-semibold">{item.label}</span><span className="mt-1 block text-sm text-navy-400">{item.desc}</span></button>)}</div><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">{rentalMode !== 'longue_duree' && <NumberField label="Prix / nuit (FCFA)" value={pricePerNight} onChange={setPricePerNight} />}{isLongTerm && <><NumberField label="Prix / mois (FCFA)" value={pricePerMonth} onChange={setPricePerMonth} /><NumberField label="Mois minimum" value={minMonths} onChange={setMinMonths} /></>}</div>{isLongTerm && <p className="rounded-lg bg-sun-50 px-3 py-2 text-sm text-navy-700">Après les équipements, l’étape suivante vous demandera la <strong>caution</strong>, l’avance, l’électricité, l’eau et les informations pratiques.</p>}</Screen>}
      {step === 'capacity' && <Screen title="Capacité & pièces"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><NumberField label="Voyageurs" value={capacity} onChange={setCapacity} />{type === 'chambre' ? <SelectField label="Salle de bain" value={privateBathroom === 'private' ? 'Privée' : 'Partagée'} onChange={(value) => setPrivateBathroom(value === 'Privée' ? 'private' : 'shared')} options={['Privée', 'Partagée']} /> : <><NumberField label="Chambres" value={bedrooms} onChange={setBedrooms} /><NumberField label="Salons" value={livingRooms} onChange={setLivingRooms} /><NumberField label="Salles de bain" value={bathrooms} onChange={setBathrooms} /></>}</div><div className="mt-5"><p className="mb-2 text-sm font-medium text-navy-700">Type de douche</p><div className="grid grid-cols-1 gap-2 sm:grid-cols-3">{[['interne', 'Douche interne'], ['externe', 'Douche externe'], ['les_deux', 'Les deux']].map(([value, label]) => <button type="button" key={value} onClick={() => setShowerType(value)} className={`min-h-[44px] rounded-lg border px-3 text-left ${showerType === value ? 'border-sun-500 bg-sun-50' : 'border-navy-100'}`}>{label}</button>)}</div></div></Screen>}
      {step === 'amenities' && <Screen title="Quels équipements proposez-vous?">{amenities.length === 0 ? <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-4 text-base text-amber-900">Aucun équipement n’est actuellement configuré dans la base de données. Les cases apparaîtront ici dès que les équipements auront été ajoutés dans la table <strong>amenities</strong>.</div> : <div className="space-y-5">{CATEGORIES.map((category) => { const items = amenities.filter((item) => amenityCategory(item.category) === category.key); if (!items.length) return null; return <div key={category.key}><h3 className="mb-2 font-display text-lg font-bold text-navy-800">{category.label}</h3><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{items.map((item) => { const Icon = iconFor(item.icon); const checked = selectedAmenities.includes(item.id); return <label key={item.id} className="flex min-w-0 items-center gap-2 rounded-lg border border-navy-100 px-3 py-3 text-base"><input type="checkbox" checked={checked} onChange={(e) => setSelectedAmenities((current) => e.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} /><Icon className="h-4 w-4 shrink-0 text-sun-500" />{item.label}</label>; })}</div></div>; })}</div>}</Screen>}
      {step === 'long-term' && <Screen title="Informations longue durée"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><NumberField label="Caution (FCFA)" value={depositAmount} onChange={setDepositAmount} /><NumberField label="Mois d'avance demandés" value={advanceMonths} onChange={setAdvanceMonths} /><SelectField label="Type d'électricité" value={electricityType} onChange={setElectricityType} options={[{ value: 'compteur_individuel', label: 'Compteur individuel' }, { value: 'compteur_partage', label: 'Compteur partagé' }, { value: 'groupe_electrogene', label: 'Groupe électrogène' }, { value: 'aucun', label: 'Aucun' }]} /><SelectField label="Source d'eau" value={waterSource} onChange={setWaterSource} options={[{ value: 'robinet_cde', label: 'Robinet CDE' }, { value: 'forage', label: 'Forage' }, { value: 'puits', label: 'Puits' }, { value: 'citerne', label: 'Citerne' }, { value: 'aucun', label: 'Aucun' }]} /><SelectField label="Accès à la route" value={roadAccess} onChange={setRoadAccess} options={[{ value: 'bord_route_bitumee', label: 'Bord de route bitumée' }, { value: 'proche_route_moins_100m', label: 'À moins de 100m' }, { value: 'acces_non_bitume', label: 'Accès non bitumé' }, { value: 'eloigne_de_la_route', label: 'Éloigné de la route' }]} /></div><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><TriStateField label="Clôturé" value={isFenced} onChange={setIsFenced} /><TriStateField label="Portail" value={hasGate} onChange={setHasGate} /><TriStateField label="Meublé" value={isFurnished} onChange={setIsFurnished} /></div></Screen>}
      {step === 'details' && <Screen title="Titre & description"><label className="block"><span className="mb-1 block text-sm font-medium">Titre de l'annonce</span><input value={title} onChange={(e) => setTitle(e.target.value)} className="w-full min-h-[44px] rounded-lg border border-navy-100 px-3 text-base" placeholder="Superbe villa vue mer" /></label><label className="block"><span className="mb-1 block text-sm font-medium">Description</span><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={4} className="w-full rounded-lg border border-navy-100 px-3 py-3 text-base" /></label><label className="block"><span className="mb-1 block text-sm font-medium">Règles de la maison</span><textarea value={houseRules} onChange={(e) => setHouseRules(e.target.value)} rows={3} className="w-full rounded-lg border border-navy-100 px-3 py-3 text-base" /></label></Screen>}
      {step === 'location' && <Screen title="Où se trouve votre logement?"><input value={quartier} onChange={(e) => setQuartier(e.target.value)} className="w-full min-h-[44px] rounded-lg border border-navy-100 px-3 text-base" placeholder="Quartier" /><input value={address} onChange={(e) => setAddress(e.target.value)} className="w-full min-h-[44px] rounded-lg border border-navy-100 px-3 text-base" placeholder="Adresse (optionnel)" /><LocationPicker initialLat={latitude} initialLng={longitude} onChange={({ lat, lng }) => { setLatitude(lat); setLongitude(lng); }} /></Screen>}
      {step === 'photos' && <Screen title={`Photos du logement (${photos.length}/5)`}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map((photo) => <div key={photo.id} className="aspect-[4/3] overflow-hidden rounded-xl"><img src={photo.previewUrl} alt="Aperçu" className="h-full w-full object-cover" /></div>)}{photos.length < 5 && <label className="flex aspect-[4/3] cursor-pointer items-center justify-center rounded-xl border-2 border-dashed border-navy-200 text-center text-sm font-semibold">Ajouter une photo<input type="file" accept="image/*" multiple onChange={handlePhotoSelect} className="hidden" /></label>}</div></Screen>}
      {step === 'contact' && <Screen title="Contact & validation"><input type="tel" name="contact_phone" value={contactPhone} onChange={(e) => setContactPhone(e.target.value)} className="w-full min-h-[44px] rounded-lg border border-navy-100 px-3 text-base" placeholder="Téléphone de contact" /><div className="mt-5 rounded-xl bg-navy-50 p-4 text-base text-navy-700"><strong>{selectedTypeLabel}</strong> · {capacity} voyageurs</div></Screen>}
      {error && <div className="mt-5 rounded-lg border border-red-200 bg-red-50 px-3 py-3 text-sm font-medium text-red-700">{error}</div>}
      <div className="mt-7 flex items-center justify-between border-t border-navy-100 pt-5"><button type="button" disabled={stepIndex === 0 || submitting} onClick={() => goTo(stepIndex - 1)} className="rounded-full border border-navy-200 px-5 py-2.5 text-sm font-medium disabled:invisible">← Précédent</button>{stepIndex < steps.length - 1 ? <button type="button" onClick={handleNext} className="rounded-full bg-sun-500 px-6 py-2.5 text-sm font-semibold text-white shadow-md">Suivant →</button> : <button type="submit" disabled={submitting} className="rounded-full bg-sun-500 px-6 py-2.5 text-sm font-semibold text-white shadow-md disabled:opacity-60">{submitting ? 'Publication...' : 'Publier mon logement'}</button>}</div>
    </form></div>;
}